export const UPDATE_CRYPTO_CURR_DATA = "UPDATE_CRYPTO_CURR_DATA";
export const START_WATCHER_TASK = "START_WATCHER_TASK";
export const STOP_WATCHER_TASK = "STOP_WATCHER_TASK";
export const CHANGE_SORT = "CHANGE_SORT";
export const SELECT_CURRENCY = "SELECT_CURRENCY";
export const REQUEST_CRYPTO_CURR_DATA = "REQUEST_CRYPTO_CURR_DATA";
